### ISSUE TITLE
Is this right: offsets.topic.replication.factor={{ default_replication_factor }}

### ISSUE THREAD

**Issue by mmm-micro** [macunha1/ansible-confluent-kafka#12]
Hi, 

Is this what you wanted to do in, https://github.com/macunha1/confluent-kafka-role/blob/master/templates/kafka.properties.j2:

`offsets.topic.replication.factor={{ default_replication_factor }}`

As this only sets the offsets topic replication factor not the default replication factor for all the automatically created topics.

Should it be:

`default.replication.factor={{ default_replication_factor }}`

?

**Comment by macunha1** [comment]
Hi,

Thank you for pointing that out, the variable name was unclear indeed.
Your issue was solved by https://github.com/macunha1/confluent-kafka-role/pull/13
