### ISSUE TITLE
Scala version

### ISSUE THREAD

**Issue by aemadrid-twx** [macunha1/ansible-confluent-kafka#17]
It doesn't look like scala_version is needed for newer versions of Confluent Platform. It seems that breaks starting on 6.

**Comment by macunha1** [comment]
@aemadrid-twx how can I replicate your issue?

Using the defaults from `master` the workflow is still passing, I guess that is for newer versions right? Either that or I need to also implement Molecule and sophisticated testing.

In any case, there are some changes pushed to https://github.com/macunha1/ansible-confluent-kafka/tree/upgrade-to-confluent-7.2.1. ATM I won't be able to test that, but in case you would like to give it a try I would appreciate the feedback!

**Comment by aemadrid** [comment]
I was trying it with 7.2.1 and it seems they changed the naming so they don't use the Scala version anymore. I will give it a try but my other complication is that I'm on an M1 mac so this adds the whole arm64 complication. I will let you know how the testing goes.

**Comment by macunha1** [comment]
@aemadrid oh it makes sense then. Yeah, for that we need the changes from https://github.com/macunha1/ansible-confluent-kafka/tree/upgrade-to-confluent-7.2.1. I am going to merge it, please LMK if it works as expected for you ;)
