### ISSUE TITLE
,Error

### ISSUE THREAD

**Issue by gowrintza** [macunha1/ansible-confluent-kafka#18]
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:            kafka_init_memory_head_with_units) }}): '>' not supported between instances of 'str' and 'int'
failed: [ansiblenode2] (item={'template': 'kafka-env.sh.j2', 'name': 'kafka-env.sh', 'group': ['ansiblenode1', 'ansiblenode2', 'ansiblenode3']}) => {"ansible_loop_var": "item", "changed": false, "item": {"group": ["ansiblenode1", "ansiblenode2", "ansiblenode3"], "name": "kafka-env.sh", "template": "kafka-env.sh.j2"}, "msg": "AnsibleError: An unhandled exception occurred while templating '{{ (ansible_memtotal_gb_sqrt > 1) |\n   ternary((ansible_memtotal_gb_sqrt | string) + 'G',\n           kafka_init_memory_head_with_units) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unexpected templating type error occurred on ({{ (ansible_memtotal_gb_sqrt > 1) |\n   ternary((ansible_memtotal_gb_sqrt | string) + 'G',\n           kafka_init_memory_head_with_units) }}): '>' not supported between instances of 'str' and 'int'"}

**Comment by macunha1** [comment]
@gowrintza thank you for pointing that out! This reminds me I need to fix the CI

Just pushed some fixes at https://github.com/macunha1/ansible-confluent-kafka/commit/f0b168a640c8555d8e2cdb6478a87894f5076be2

Please LMK if that works for you @gowrintza
